name: 'Debugger'
description: 'Interactive debugger for GitHub Action with tmate.io'
on: [push]
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Debug Session
      uses: csexton/debugger-action@master
